package com.mapper.generate;

import com.entity.OauthSystem;
import com.entity.OauthSystemExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface OauthSystemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_system
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    int countByExample(OauthSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_system
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    int deleteByExample(OauthSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_system
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    int deleteByPrimaryKey(Integer systemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_system
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    int insert(OauthSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_system
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    int insertSelective(OauthSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_system
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    List<OauthSystem> selectByExample(OauthSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_system
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    OauthSystem selectByPrimaryKey(Integer systemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_system
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    int updateByExampleSelective(@Param("record") OauthSystem record, @Param("example") OauthSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_system
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    int updateByExample(@Param("record") OauthSystem record, @Param("example") OauthSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_system
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    int updateByPrimaryKeySelective(OauthSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_system
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    int updateByPrimaryKey(OauthSystem record);
}