package com.mapper.generate;

import com.entity.OauthResource;
import com.entity.OauthResourceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OauthResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_resource
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    int countByExample(OauthResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_resource
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    int deleteByExample(OauthResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_resource
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    int deleteByPrimaryKey(Integer resourceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_resource
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    int insert(OauthResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_resource
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    int insertSelective(OauthResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_resource
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    List<OauthResource> selectByExample(OauthResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_resource
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    OauthResource selectByPrimaryKey(Integer resourceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_resource
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    int updateByExampleSelective(@Param("record") OauthResource record, @Param("example") OauthResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_resource
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    int updateByExample(@Param("record") OauthResource record, @Param("example") OauthResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_resource
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    int updateByPrimaryKeySelective(OauthResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_resource
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    int updateByPrimaryKey(OauthResource record);
}