package com.mapper.generate;

import com.entity.OauthSystemResource;
import com.entity.OauthSystemResourceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OauthSystemResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_system_resource
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    int countByExample(OauthSystemResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_system_resource
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    int deleteByExample(OauthSystemResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_system_resource
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    int deleteByPrimaryKey(Integer oauthSystemResourceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_system_resource
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    int insert(OauthSystemResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_system_resource
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    int insertSelective(OauthSystemResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_system_resource
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    List<OauthSystemResource> selectByExample(OauthSystemResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_system_resource
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    OauthSystemResource selectByPrimaryKey(Integer oauthSystemResourceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_system_resource
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    int updateByExampleSelective(@Param("record") OauthSystemResource record, @Param("example") OauthSystemResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_system_resource
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    int updateByExample(@Param("record") OauthSystemResource record, @Param("example") OauthSystemResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_system_resource
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    int updateByPrimaryKeySelective(OauthSystemResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_system_resource
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    int updateByPrimaryKey(OauthSystemResource record);
}