package com.mapper.generate;

import com.entity.UserRoleResource;
import com.entity.UserRoleResourceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserRoleResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_resource
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    int countByExample(UserRoleResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_resource
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    int deleteByExample(UserRoleResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_resource
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    int deleteByPrimaryKey(Integer roleResourceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_resource
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    int insert(UserRoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_resource
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    int insertSelective(UserRoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_resource
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    List<UserRoleResource> selectByExample(UserRoleResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_resource
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    UserRoleResource selectByPrimaryKey(Integer roleResourceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_resource
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    int updateByExampleSelective(@Param("record") UserRoleResource record, @Param("example") UserRoleResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_resource
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    int updateByExample(@Param("record") UserRoleResource record, @Param("example") UserRoleResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_resource
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    int updateByPrimaryKeySelective(UserRoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_resource
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    int updateByPrimaryKey(UserRoleResource record);
}