package com.entity;

import java.io.Serializable;
import java.util.Date;

public class OauthResource implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oauth_resource
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    private static final long serialVersionUID = 1L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_resource.resource_id
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    private Integer resourceId;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_resource.parent
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    private Integer parent;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_resource.name
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    private String name;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_resource.level
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    private Byte level;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_resource.url
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    private String url;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_resource.sort
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    private Byte sort;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_resource.code
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    private String code;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_resource.type
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    private Byte type;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_resource.page
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    private String page;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_resource.status
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    private Byte status;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_resource.system
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    private String system;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_resource.source_type
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    private Boolean sourceType;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_resource.create_time
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    private Date createTime;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_resource.update_time
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_resource.resource_id
     *
     * @return the value of oauth_resource.resource_id
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    public Integer getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_resource.resource_id
     *
     * @param resourceId the value for oauth_resource.resource_id
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    public void setResourceId(Integer resourceId) {
        this.resourceId = resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_resource.parent
     *
     * @return the value of oauth_resource.parent
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    public Integer getParent() {
        return parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_resource.parent
     *
     * @param parent the value for oauth_resource.parent
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    public void setParent(Integer parent) {
        this.parent = parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_resource.name
     *
     * @return the value of oauth_resource.name
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_resource.name
     *
     * @param name the value for oauth_resource.name
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_resource.level
     *
     * @return the value of oauth_resource.level
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    public Byte getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_resource.level
     *
     * @param level the value for oauth_resource.level
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    public void setLevel(Byte level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_resource.url
     *
     * @return the value of oauth_resource.url
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_resource.url
     *
     * @param url the value for oauth_resource.url
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_resource.sort
     *
     * @return the value of oauth_resource.sort
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    public Byte getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_resource.sort
     *
     * @param sort the value for oauth_resource.sort
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    public void setSort(Byte sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_resource.code
     *
     * @return the value of oauth_resource.code
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_resource.code
     *
     * @param code the value for oauth_resource.code
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_resource.type
     *
     * @return the value of oauth_resource.type
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_resource.type
     *
     * @param type the value for oauth_resource.type
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_resource.page
     *
     * @return the value of oauth_resource.page
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    public String getPage() {
        return page;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_resource.page
     *
     * @param page the value for oauth_resource.page
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    public void setPage(String page) {
        this.page = page == null ? null : page.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_resource.status
     *
     * @return the value of oauth_resource.status
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_resource.status
     *
     * @param status the value for oauth_resource.status
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_resource.system
     *
     * @return the value of oauth_resource.system
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    public String getSystem() {
        return system;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_resource.system
     *
     * @param system the value for oauth_resource.system
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    public void setSystem(String system) {
        this.system = system == null ? null : system.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_resource.source_type
     *
     * @return the value of oauth_resource.source_type
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    public Boolean getSourceType() {
        return sourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_resource.source_type
     *
     * @param sourceType the value for oauth_resource.source_type
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    public void setSourceType(Boolean sourceType) {
        this.sourceType = sourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_resource.create_time
     *
     * @return the value of oauth_resource.create_time
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_resource.create_time
     *
     * @param createTime the value for oauth_resource.create_time
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_resource.update_time
     *
     * @return the value of oauth_resource.update_time
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_resource.update_time
     *
     * @param updateTime the value for oauth_resource.update_time
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}