package com.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OauthClientDetailsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oauth_client_details
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oauth_client_details
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oauth_client_details
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    public OauthClientDetailsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_client_details
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table oauth_client_details
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("`id` is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("`id` is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("`id` =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("`id` <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("`id` >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("`id` >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("`id` <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("`id` <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("`id` in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("`id` not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("`id` between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("`id` not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andClientIdIsNull() {
            addCriterion("`client_id` is null");
            return (Criteria) this;
        }

        public Criteria andClientIdIsNotNull() {
            addCriterion("`client_id` is not null");
            return (Criteria) this;
        }

        public Criteria andClientIdEqualTo(String value) {
            addCriterion("`client_id` =", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdNotEqualTo(String value) {
            addCriterion("`client_id` <>", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdGreaterThan(String value) {
            addCriterion("`client_id` >", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdGreaterThanOrEqualTo(String value) {
            addCriterion("`client_id` >=", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdLessThan(String value) {
            addCriterion("`client_id` <", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdLessThanOrEqualTo(String value) {
            addCriterion("`client_id` <=", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdLike(String value) {
            addCriterion("`client_id` like", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdNotLike(String value) {
            addCriterion("`client_id` not like", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdIn(List<String> values) {
            addCriterion("`client_id` in", values, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdNotIn(List<String> values) {
            addCriterion("`client_id` not in", values, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdBetween(String value1, String value2) {
            addCriterion("`client_id` between", value1, value2, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdNotBetween(String value1, String value2) {
            addCriterion("`client_id` not between", value1, value2, "clientId");
            return (Criteria) this;
        }

        public Criteria andResourceIdsIsNull() {
            addCriterion("`resource_ids` is null");
            return (Criteria) this;
        }

        public Criteria andResourceIdsIsNotNull() {
            addCriterion("`resource_ids` is not null");
            return (Criteria) this;
        }

        public Criteria andResourceIdsEqualTo(String value) {
            addCriterion("`resource_ids` =", value, "resourceIds");
            return (Criteria) this;
        }

        public Criteria andResourceIdsNotEqualTo(String value) {
            addCriterion("`resource_ids` <>", value, "resourceIds");
            return (Criteria) this;
        }

        public Criteria andResourceIdsGreaterThan(String value) {
            addCriterion("`resource_ids` >", value, "resourceIds");
            return (Criteria) this;
        }

        public Criteria andResourceIdsGreaterThanOrEqualTo(String value) {
            addCriterion("`resource_ids` >=", value, "resourceIds");
            return (Criteria) this;
        }

        public Criteria andResourceIdsLessThan(String value) {
            addCriterion("`resource_ids` <", value, "resourceIds");
            return (Criteria) this;
        }

        public Criteria andResourceIdsLessThanOrEqualTo(String value) {
            addCriterion("`resource_ids` <=", value, "resourceIds");
            return (Criteria) this;
        }

        public Criteria andResourceIdsLike(String value) {
            addCriterion("`resource_ids` like", value, "resourceIds");
            return (Criteria) this;
        }

        public Criteria andResourceIdsNotLike(String value) {
            addCriterion("`resource_ids` not like", value, "resourceIds");
            return (Criteria) this;
        }

        public Criteria andResourceIdsIn(List<String> values) {
            addCriterion("`resource_ids` in", values, "resourceIds");
            return (Criteria) this;
        }

        public Criteria andResourceIdsNotIn(List<String> values) {
            addCriterion("`resource_ids` not in", values, "resourceIds");
            return (Criteria) this;
        }

        public Criteria andResourceIdsBetween(String value1, String value2) {
            addCriterion("`resource_ids` between", value1, value2, "resourceIds");
            return (Criteria) this;
        }

        public Criteria andResourceIdsNotBetween(String value1, String value2) {
            addCriterion("`resource_ids` not between", value1, value2, "resourceIds");
            return (Criteria) this;
        }

        public Criteria andClientSecretIsNull() {
            addCriterion("`client_secret` is null");
            return (Criteria) this;
        }

        public Criteria andClientSecretIsNotNull() {
            addCriterion("`client_secret` is not null");
            return (Criteria) this;
        }

        public Criteria andClientSecretEqualTo(String value) {
            addCriterion("`client_secret` =", value, "clientSecret");
            return (Criteria) this;
        }

        public Criteria andClientSecretNotEqualTo(String value) {
            addCriterion("`client_secret` <>", value, "clientSecret");
            return (Criteria) this;
        }

        public Criteria andClientSecretGreaterThan(String value) {
            addCriterion("`client_secret` >", value, "clientSecret");
            return (Criteria) this;
        }

        public Criteria andClientSecretGreaterThanOrEqualTo(String value) {
            addCriterion("`client_secret` >=", value, "clientSecret");
            return (Criteria) this;
        }

        public Criteria andClientSecretLessThan(String value) {
            addCriterion("`client_secret` <", value, "clientSecret");
            return (Criteria) this;
        }

        public Criteria andClientSecretLessThanOrEqualTo(String value) {
            addCriterion("`client_secret` <=", value, "clientSecret");
            return (Criteria) this;
        }

        public Criteria andClientSecretLike(String value) {
            addCriterion("`client_secret` like", value, "clientSecret");
            return (Criteria) this;
        }

        public Criteria andClientSecretNotLike(String value) {
            addCriterion("`client_secret` not like", value, "clientSecret");
            return (Criteria) this;
        }

        public Criteria andClientSecretIn(List<String> values) {
            addCriterion("`client_secret` in", values, "clientSecret");
            return (Criteria) this;
        }

        public Criteria andClientSecretNotIn(List<String> values) {
            addCriterion("`client_secret` not in", values, "clientSecret");
            return (Criteria) this;
        }

        public Criteria andClientSecretBetween(String value1, String value2) {
            addCriterion("`client_secret` between", value1, value2, "clientSecret");
            return (Criteria) this;
        }

        public Criteria andClientSecretNotBetween(String value1, String value2) {
            addCriterion("`client_secret` not between", value1, value2, "clientSecret");
            return (Criteria) this;
        }

        public Criteria andScopeIsNull() {
            addCriterion("`scope` is null");
            return (Criteria) this;
        }

        public Criteria andScopeIsNotNull() {
            addCriterion("`scope` is not null");
            return (Criteria) this;
        }

        public Criteria andScopeEqualTo(String value) {
            addCriterion("`scope` =", value, "scope");
            return (Criteria) this;
        }

        public Criteria andScopeNotEqualTo(String value) {
            addCriterion("`scope` <>", value, "scope");
            return (Criteria) this;
        }

        public Criteria andScopeGreaterThan(String value) {
            addCriterion("`scope` >", value, "scope");
            return (Criteria) this;
        }

        public Criteria andScopeGreaterThanOrEqualTo(String value) {
            addCriterion("`scope` >=", value, "scope");
            return (Criteria) this;
        }

        public Criteria andScopeLessThan(String value) {
            addCriterion("`scope` <", value, "scope");
            return (Criteria) this;
        }

        public Criteria andScopeLessThanOrEqualTo(String value) {
            addCriterion("`scope` <=", value, "scope");
            return (Criteria) this;
        }

        public Criteria andScopeLike(String value) {
            addCriterion("`scope` like", value, "scope");
            return (Criteria) this;
        }

        public Criteria andScopeNotLike(String value) {
            addCriterion("`scope` not like", value, "scope");
            return (Criteria) this;
        }

        public Criteria andScopeIn(List<String> values) {
            addCriterion("`scope` in", values, "scope");
            return (Criteria) this;
        }

        public Criteria andScopeNotIn(List<String> values) {
            addCriterion("`scope` not in", values, "scope");
            return (Criteria) this;
        }

        public Criteria andScopeBetween(String value1, String value2) {
            addCriterion("`scope` between", value1, value2, "scope");
            return (Criteria) this;
        }

        public Criteria andScopeNotBetween(String value1, String value2) {
            addCriterion("`scope` not between", value1, value2, "scope");
            return (Criteria) this;
        }

        public Criteria andAuthorizedGrantTypesIsNull() {
            addCriterion("`authorized_grant_types` is null");
            return (Criteria) this;
        }

        public Criteria andAuthorizedGrantTypesIsNotNull() {
            addCriterion("`authorized_grant_types` is not null");
            return (Criteria) this;
        }

        public Criteria andAuthorizedGrantTypesEqualTo(String value) {
            addCriterion("`authorized_grant_types` =", value, "authorizedGrantTypes");
            return (Criteria) this;
        }

        public Criteria andAuthorizedGrantTypesNotEqualTo(String value) {
            addCriterion("`authorized_grant_types` <>", value, "authorizedGrantTypes");
            return (Criteria) this;
        }

        public Criteria andAuthorizedGrantTypesGreaterThan(String value) {
            addCriterion("`authorized_grant_types` >", value, "authorizedGrantTypes");
            return (Criteria) this;
        }

        public Criteria andAuthorizedGrantTypesGreaterThanOrEqualTo(String value) {
            addCriterion("`authorized_grant_types` >=", value, "authorizedGrantTypes");
            return (Criteria) this;
        }

        public Criteria andAuthorizedGrantTypesLessThan(String value) {
            addCriterion("`authorized_grant_types` <", value, "authorizedGrantTypes");
            return (Criteria) this;
        }

        public Criteria andAuthorizedGrantTypesLessThanOrEqualTo(String value) {
            addCriterion("`authorized_grant_types` <=", value, "authorizedGrantTypes");
            return (Criteria) this;
        }

        public Criteria andAuthorizedGrantTypesLike(String value) {
            addCriterion("`authorized_grant_types` like", value, "authorizedGrantTypes");
            return (Criteria) this;
        }

        public Criteria andAuthorizedGrantTypesNotLike(String value) {
            addCriterion("`authorized_grant_types` not like", value, "authorizedGrantTypes");
            return (Criteria) this;
        }

        public Criteria andAuthorizedGrantTypesIn(List<String> values) {
            addCriterion("`authorized_grant_types` in", values, "authorizedGrantTypes");
            return (Criteria) this;
        }

        public Criteria andAuthorizedGrantTypesNotIn(List<String> values) {
            addCriterion("`authorized_grant_types` not in", values, "authorizedGrantTypes");
            return (Criteria) this;
        }

        public Criteria andAuthorizedGrantTypesBetween(String value1, String value2) {
            addCriterion("`authorized_grant_types` between", value1, value2, "authorizedGrantTypes");
            return (Criteria) this;
        }

        public Criteria andAuthorizedGrantTypesNotBetween(String value1, String value2) {
            addCriterion("`authorized_grant_types` not between", value1, value2, "authorizedGrantTypes");
            return (Criteria) this;
        }

        public Criteria andWebServerRedirectUriIsNull() {
            addCriterion("`web_server_redirect_uri` is null");
            return (Criteria) this;
        }

        public Criteria andWebServerRedirectUriIsNotNull() {
            addCriterion("`web_server_redirect_uri` is not null");
            return (Criteria) this;
        }

        public Criteria andWebServerRedirectUriEqualTo(String value) {
            addCriterion("`web_server_redirect_uri` =", value, "webServerRedirectUri");
            return (Criteria) this;
        }

        public Criteria andWebServerRedirectUriNotEqualTo(String value) {
            addCriterion("`web_server_redirect_uri` <>", value, "webServerRedirectUri");
            return (Criteria) this;
        }

        public Criteria andWebServerRedirectUriGreaterThan(String value) {
            addCriterion("`web_server_redirect_uri` >", value, "webServerRedirectUri");
            return (Criteria) this;
        }

        public Criteria andWebServerRedirectUriGreaterThanOrEqualTo(String value) {
            addCriterion("`web_server_redirect_uri` >=", value, "webServerRedirectUri");
            return (Criteria) this;
        }

        public Criteria andWebServerRedirectUriLessThan(String value) {
            addCriterion("`web_server_redirect_uri` <", value, "webServerRedirectUri");
            return (Criteria) this;
        }

        public Criteria andWebServerRedirectUriLessThanOrEqualTo(String value) {
            addCriterion("`web_server_redirect_uri` <=", value, "webServerRedirectUri");
            return (Criteria) this;
        }

        public Criteria andWebServerRedirectUriLike(String value) {
            addCriterion("`web_server_redirect_uri` like", value, "webServerRedirectUri");
            return (Criteria) this;
        }

        public Criteria andWebServerRedirectUriNotLike(String value) {
            addCriterion("`web_server_redirect_uri` not like", value, "webServerRedirectUri");
            return (Criteria) this;
        }

        public Criteria andWebServerRedirectUriIn(List<String> values) {
            addCriterion("`web_server_redirect_uri` in", values, "webServerRedirectUri");
            return (Criteria) this;
        }

        public Criteria andWebServerRedirectUriNotIn(List<String> values) {
            addCriterion("`web_server_redirect_uri` not in", values, "webServerRedirectUri");
            return (Criteria) this;
        }

        public Criteria andWebServerRedirectUriBetween(String value1, String value2) {
            addCriterion("`web_server_redirect_uri` between", value1, value2, "webServerRedirectUri");
            return (Criteria) this;
        }

        public Criteria andWebServerRedirectUriNotBetween(String value1, String value2) {
            addCriterion("`web_server_redirect_uri` not between", value1, value2, "webServerRedirectUri");
            return (Criteria) this;
        }

        public Criteria andAuthoritiesIsNull() {
            addCriterion("`authorities` is null");
            return (Criteria) this;
        }

        public Criteria andAuthoritiesIsNotNull() {
            addCriterion("`authorities` is not null");
            return (Criteria) this;
        }

        public Criteria andAuthoritiesEqualTo(String value) {
            addCriterion("`authorities` =", value, "authorities");
            return (Criteria) this;
        }

        public Criteria andAuthoritiesNotEqualTo(String value) {
            addCriterion("`authorities` <>", value, "authorities");
            return (Criteria) this;
        }

        public Criteria andAuthoritiesGreaterThan(String value) {
            addCriterion("`authorities` >", value, "authorities");
            return (Criteria) this;
        }

        public Criteria andAuthoritiesGreaterThanOrEqualTo(String value) {
            addCriterion("`authorities` >=", value, "authorities");
            return (Criteria) this;
        }

        public Criteria andAuthoritiesLessThan(String value) {
            addCriterion("`authorities` <", value, "authorities");
            return (Criteria) this;
        }

        public Criteria andAuthoritiesLessThanOrEqualTo(String value) {
            addCriterion("`authorities` <=", value, "authorities");
            return (Criteria) this;
        }

        public Criteria andAuthoritiesLike(String value) {
            addCriterion("`authorities` like", value, "authorities");
            return (Criteria) this;
        }

        public Criteria andAuthoritiesNotLike(String value) {
            addCriterion("`authorities` not like", value, "authorities");
            return (Criteria) this;
        }

        public Criteria andAuthoritiesIn(List<String> values) {
            addCriterion("`authorities` in", values, "authorities");
            return (Criteria) this;
        }

        public Criteria andAuthoritiesNotIn(List<String> values) {
            addCriterion("`authorities` not in", values, "authorities");
            return (Criteria) this;
        }

        public Criteria andAuthoritiesBetween(String value1, String value2) {
            addCriterion("`authorities` between", value1, value2, "authorities");
            return (Criteria) this;
        }

        public Criteria andAuthoritiesNotBetween(String value1, String value2) {
            addCriterion("`authorities` not between", value1, value2, "authorities");
            return (Criteria) this;
        }

        public Criteria andAccessTokenValidityIsNull() {
            addCriterion("`access_token_validity` is null");
            return (Criteria) this;
        }

        public Criteria andAccessTokenValidityIsNotNull() {
            addCriterion("`access_token_validity` is not null");
            return (Criteria) this;
        }

        public Criteria andAccessTokenValidityEqualTo(Double value) {
            addCriterion("`access_token_validity` =", value, "accessTokenValidity");
            return (Criteria) this;
        }

        public Criteria andAccessTokenValidityNotEqualTo(Double value) {
            addCriterion("`access_token_validity` <>", value, "accessTokenValidity");
            return (Criteria) this;
        }

        public Criteria andAccessTokenValidityGreaterThan(Double value) {
            addCriterion("`access_token_validity` >", value, "accessTokenValidity");
            return (Criteria) this;
        }

        public Criteria andAccessTokenValidityGreaterThanOrEqualTo(Double value) {
            addCriterion("`access_token_validity` >=", value, "accessTokenValidity");
            return (Criteria) this;
        }

        public Criteria andAccessTokenValidityLessThan(Double value) {
            addCriterion("`access_token_validity` <", value, "accessTokenValidity");
            return (Criteria) this;
        }

        public Criteria andAccessTokenValidityLessThanOrEqualTo(Double value) {
            addCriterion("`access_token_validity` <=", value, "accessTokenValidity");
            return (Criteria) this;
        }

        public Criteria andAccessTokenValidityIn(List<Double> values) {
            addCriterion("`access_token_validity` in", values, "accessTokenValidity");
            return (Criteria) this;
        }

        public Criteria andAccessTokenValidityNotIn(List<Double> values) {
            addCriterion("`access_token_validity` not in", values, "accessTokenValidity");
            return (Criteria) this;
        }

        public Criteria andAccessTokenValidityBetween(Double value1, Double value2) {
            addCriterion("`access_token_validity` between", value1, value2, "accessTokenValidity");
            return (Criteria) this;
        }

        public Criteria andAccessTokenValidityNotBetween(Double value1, Double value2) {
            addCriterion("`access_token_validity` not between", value1, value2, "accessTokenValidity");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenValidityIsNull() {
            addCriterion("`refresh_token_validity` is null");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenValidityIsNotNull() {
            addCriterion("`refresh_token_validity` is not null");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenValidityEqualTo(Double value) {
            addCriterion("`refresh_token_validity` =", value, "refreshTokenValidity");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenValidityNotEqualTo(Double value) {
            addCriterion("`refresh_token_validity` <>", value, "refreshTokenValidity");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenValidityGreaterThan(Double value) {
            addCriterion("`refresh_token_validity` >", value, "refreshTokenValidity");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenValidityGreaterThanOrEqualTo(Double value) {
            addCriterion("`refresh_token_validity` >=", value, "refreshTokenValidity");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenValidityLessThan(Double value) {
            addCriterion("`refresh_token_validity` <", value, "refreshTokenValidity");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenValidityLessThanOrEqualTo(Double value) {
            addCriterion("`refresh_token_validity` <=", value, "refreshTokenValidity");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenValidityIn(List<Double> values) {
            addCriterion("`refresh_token_validity` in", values, "refreshTokenValidity");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenValidityNotIn(List<Double> values) {
            addCriterion("`refresh_token_validity` not in", values, "refreshTokenValidity");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenValidityBetween(Double value1, Double value2) {
            addCriterion("`refresh_token_validity` between", value1, value2, "refreshTokenValidity");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenValidityNotBetween(Double value1, Double value2) {
            addCriterion("`refresh_token_validity` not between", value1, value2, "refreshTokenValidity");
            return (Criteria) this;
        }

        public Criteria andAutoapproveIsNull() {
            addCriterion("`autoapprove` is null");
            return (Criteria) this;
        }

        public Criteria andAutoapproveIsNotNull() {
            addCriterion("`autoapprove` is not null");
            return (Criteria) this;
        }

        public Criteria andAutoapproveEqualTo(String value) {
            addCriterion("`autoapprove` =", value, "autoapprove");
            return (Criteria) this;
        }

        public Criteria andAutoapproveNotEqualTo(String value) {
            addCriterion("`autoapprove` <>", value, "autoapprove");
            return (Criteria) this;
        }

        public Criteria andAutoapproveGreaterThan(String value) {
            addCriterion("`autoapprove` >", value, "autoapprove");
            return (Criteria) this;
        }

        public Criteria andAutoapproveGreaterThanOrEqualTo(String value) {
            addCriterion("`autoapprove` >=", value, "autoapprove");
            return (Criteria) this;
        }

        public Criteria andAutoapproveLessThan(String value) {
            addCriterion("`autoapprove` <", value, "autoapprove");
            return (Criteria) this;
        }

        public Criteria andAutoapproveLessThanOrEqualTo(String value) {
            addCriterion("`autoapprove` <=", value, "autoapprove");
            return (Criteria) this;
        }

        public Criteria andAutoapproveLike(String value) {
            addCriterion("`autoapprove` like", value, "autoapprove");
            return (Criteria) this;
        }

        public Criteria andAutoapproveNotLike(String value) {
            addCriterion("`autoapprove` not like", value, "autoapprove");
            return (Criteria) this;
        }

        public Criteria andAutoapproveIn(List<String> values) {
            addCriterion("`autoapprove` in", values, "autoapprove");
            return (Criteria) this;
        }

        public Criteria andAutoapproveNotIn(List<String> values) {
            addCriterion("`autoapprove` not in", values, "autoapprove");
            return (Criteria) this;
        }

        public Criteria andAutoapproveBetween(String value1, String value2) {
            addCriterion("`autoapprove` between", value1, value2, "autoapprove");
            return (Criteria) this;
        }

        public Criteria andAutoapproveNotBetween(String value1, String value2) {
            addCriterion("`autoapprove` not between", value1, value2, "autoapprove");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("`create_time` is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("`create_time` is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("`create_time` =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("`create_time` <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("`create_time` >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("`create_time` >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("`create_time` <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("`create_time` <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("`create_time` in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("`create_time` not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("`create_time` between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("`create_time` not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("`update_time` is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("`update_time` is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("`update_time` =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("`update_time` <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("`update_time` >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("`update_time` >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("`update_time` <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("`update_time` <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("`update_time` in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("`update_time` not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("`update_time` between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("`update_time` not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andDailyAccessNumIsNull() {
            addCriterion("`daily_access_num` is null");
            return (Criteria) this;
        }

        public Criteria andDailyAccessNumIsNotNull() {
            addCriterion("`daily_access_num` is not null");
            return (Criteria) this;
        }

        public Criteria andDailyAccessNumEqualTo(Integer value) {
            addCriterion("`daily_access_num` =", value, "dailyAccessNum");
            return (Criteria) this;
        }

        public Criteria andDailyAccessNumNotEqualTo(Integer value) {
            addCriterion("`daily_access_num` <>", value, "dailyAccessNum");
            return (Criteria) this;
        }

        public Criteria andDailyAccessNumGreaterThan(Integer value) {
            addCriterion("`daily_access_num` >", value, "dailyAccessNum");
            return (Criteria) this;
        }

        public Criteria andDailyAccessNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("`daily_access_num` >=", value, "dailyAccessNum");
            return (Criteria) this;
        }

        public Criteria andDailyAccessNumLessThan(Integer value) {
            addCriterion("`daily_access_num` <", value, "dailyAccessNum");
            return (Criteria) this;
        }

        public Criteria andDailyAccessNumLessThanOrEqualTo(Integer value) {
            addCriterion("`daily_access_num` <=", value, "dailyAccessNum");
            return (Criteria) this;
        }

        public Criteria andDailyAccessNumIn(List<Integer> values) {
            addCriterion("`daily_access_num` in", values, "dailyAccessNum");
            return (Criteria) this;
        }

        public Criteria andDailyAccessNumNotIn(List<Integer> values) {
            addCriterion("`daily_access_num` not in", values, "dailyAccessNum");
            return (Criteria) this;
        }

        public Criteria andDailyAccessNumBetween(Integer value1, Integer value2) {
            addCriterion("`daily_access_num` between", value1, value2, "dailyAccessNum");
            return (Criteria) this;
        }

        public Criteria andDailyAccessNumNotBetween(Integer value1, Integer value2) {
            addCriterion("`daily_access_num` not between", value1, value2, "dailyAccessNum");
            return (Criteria) this;
        }

        public Criteria andMinuteAccessNumIsNull() {
            addCriterion("`minute_access_num` is null");
            return (Criteria) this;
        }

        public Criteria andMinuteAccessNumIsNotNull() {
            addCriterion("`minute_access_num` is not null");
            return (Criteria) this;
        }

        public Criteria andMinuteAccessNumEqualTo(Integer value) {
            addCriterion("`minute_access_num` =", value, "minuteAccessNum");
            return (Criteria) this;
        }

        public Criteria andMinuteAccessNumNotEqualTo(Integer value) {
            addCriterion("`minute_access_num` <>", value, "minuteAccessNum");
            return (Criteria) this;
        }

        public Criteria andMinuteAccessNumGreaterThan(Integer value) {
            addCriterion("`minute_access_num` >", value, "minuteAccessNum");
            return (Criteria) this;
        }

        public Criteria andMinuteAccessNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("`minute_access_num` >=", value, "minuteAccessNum");
            return (Criteria) this;
        }

        public Criteria andMinuteAccessNumLessThan(Integer value) {
            addCriterion("`minute_access_num` <", value, "minuteAccessNum");
            return (Criteria) this;
        }

        public Criteria andMinuteAccessNumLessThanOrEqualTo(Integer value) {
            addCriterion("`minute_access_num` <=", value, "minuteAccessNum");
            return (Criteria) this;
        }

        public Criteria andMinuteAccessNumIn(List<Integer> values) {
            addCriterion("`minute_access_num` in", values, "minuteAccessNum");
            return (Criteria) this;
        }

        public Criteria andMinuteAccessNumNotIn(List<Integer> values) {
            addCriterion("`minute_access_num` not in", values, "minuteAccessNum");
            return (Criteria) this;
        }

        public Criteria andMinuteAccessNumBetween(Integer value1, Integer value2) {
            addCriterion("`minute_access_num` between", value1, value2, "minuteAccessNum");
            return (Criteria) this;
        }

        public Criteria andMinuteAccessNumNotBetween(Integer value1, Integer value2) {
            addCriterion("`minute_access_num` not between", value1, value2, "minuteAccessNum");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table oauth_client_details
     *
     * @mbggenerated do_not_delete_during_merge Fri Jun 02 17:07:11 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table oauth_client_details
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}