package com.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserBaseExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_base
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_base
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_base
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    public UserBaseExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_base
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUserIdIsNull() {
            addCriterion("`user_id` is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("`user_id` is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("`user_id` =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("`user_id` <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("`user_id` >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("`user_id` >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("`user_id` <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("`user_id` <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("`user_id` in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("`user_id` not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("`user_id` between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("`user_id` not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andCodeIsNull() {
            addCriterion("`code` is null");
            return (Criteria) this;
        }

        public Criteria andCodeIsNotNull() {
            addCriterion("`code` is not null");
            return (Criteria) this;
        }

        public Criteria andCodeEqualTo(String value) {
            addCriterion("`code` =", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotEqualTo(String value) {
            addCriterion("`code` <>", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThan(String value) {
            addCriterion("`code` >", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThanOrEqualTo(String value) {
            addCriterion("`code` >=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThan(String value) {
            addCriterion("`code` <", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThanOrEqualTo(String value) {
            addCriterion("`code` <=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLike(String value) {
            addCriterion("`code` like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotLike(String value) {
            addCriterion("`code` not like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeIn(List<String> values) {
            addCriterion("`code` in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotIn(List<String> values) {
            addCriterion("`code` not in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeBetween(String value1, String value2) {
            addCriterion("`code` between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotBetween(String value1, String value2) {
            addCriterion("`code` not between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andPwdIsNull() {
            addCriterion("`pwd` is null");
            return (Criteria) this;
        }

        public Criteria andPwdIsNotNull() {
            addCriterion("`pwd` is not null");
            return (Criteria) this;
        }

        public Criteria andPwdEqualTo(String value) {
            addCriterion("`pwd` =", value, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdNotEqualTo(String value) {
            addCriterion("`pwd` <>", value, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdGreaterThan(String value) {
            addCriterion("`pwd` >", value, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdGreaterThanOrEqualTo(String value) {
            addCriterion("`pwd` >=", value, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdLessThan(String value) {
            addCriterion("`pwd` <", value, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdLessThanOrEqualTo(String value) {
            addCriterion("`pwd` <=", value, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdLike(String value) {
            addCriterion("`pwd` like", value, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdNotLike(String value) {
            addCriterion("`pwd` not like", value, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdIn(List<String> values) {
            addCriterion("`pwd` in", values, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdNotIn(List<String> values) {
            addCriterion("`pwd` not in", values, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdBetween(String value1, String value2) {
            addCriterion("`pwd` between", value1, value2, "pwd");
            return (Criteria) this;
        }

        public Criteria andPwdNotBetween(String value1, String value2) {
            addCriterion("`pwd` not between", value1, value2, "pwd");
            return (Criteria) this;
        }

        public Criteria andUserRosterIsNull() {
            addCriterion("`user_roster` is null");
            return (Criteria) this;
        }

        public Criteria andUserRosterIsNotNull() {
            addCriterion("`user_roster` is not null");
            return (Criteria) this;
        }

        public Criteria andUserRosterEqualTo(String value) {
            addCriterion("`user_roster` =", value, "userRoster");
            return (Criteria) this;
        }

        public Criteria andUserRosterNotEqualTo(String value) {
            addCriterion("`user_roster` <>", value, "userRoster");
            return (Criteria) this;
        }

        public Criteria andUserRosterGreaterThan(String value) {
            addCriterion("`user_roster` >", value, "userRoster");
            return (Criteria) this;
        }

        public Criteria andUserRosterGreaterThanOrEqualTo(String value) {
            addCriterion("`user_roster` >=", value, "userRoster");
            return (Criteria) this;
        }

        public Criteria andUserRosterLessThan(String value) {
            addCriterion("`user_roster` <", value, "userRoster");
            return (Criteria) this;
        }

        public Criteria andUserRosterLessThanOrEqualTo(String value) {
            addCriterion("`user_roster` <=", value, "userRoster");
            return (Criteria) this;
        }

        public Criteria andUserRosterLike(String value) {
            addCriterion("`user_roster` like", value, "userRoster");
            return (Criteria) this;
        }

        public Criteria andUserRosterNotLike(String value) {
            addCriterion("`user_roster` not like", value, "userRoster");
            return (Criteria) this;
        }

        public Criteria andUserRosterIn(List<String> values) {
            addCriterion("`user_roster` in", values, "userRoster");
            return (Criteria) this;
        }

        public Criteria andUserRosterNotIn(List<String> values) {
            addCriterion("`user_roster` not in", values, "userRoster");
            return (Criteria) this;
        }

        public Criteria andUserRosterBetween(String value1, String value2) {
            addCriterion("`user_roster` between", value1, value2, "userRoster");
            return (Criteria) this;
        }

        public Criteria andUserRosterNotBetween(String value1, String value2) {
            addCriterion("`user_roster` not between", value1, value2, "userRoster");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNull() {
            addCriterion("`user_name` is null");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNotNull() {
            addCriterion("`user_name` is not null");
            return (Criteria) this;
        }

        public Criteria andUserNameEqualTo(String value) {
            addCriterion("`user_name` =", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotEqualTo(String value) {
            addCriterion("`user_name` <>", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThan(String value) {
            addCriterion("`user_name` >", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("`user_name` >=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThan(String value) {
            addCriterion("`user_name` <", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThanOrEqualTo(String value) {
            addCriterion("`user_name` <=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLike(String value) {
            addCriterion("`user_name` like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotLike(String value) {
            addCriterion("`user_name` not like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameIn(List<String> values) {
            addCriterion("`user_name` in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotIn(List<String> values) {
            addCriterion("`user_name` not in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameBetween(String value1, String value2) {
            addCriterion("`user_name` between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotBetween(String value1, String value2) {
            addCriterion("`user_name` not between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andDepartIdIsNull() {
            addCriterion("`depart_id` is null");
            return (Criteria) this;
        }

        public Criteria andDepartIdIsNotNull() {
            addCriterion("`depart_id` is not null");
            return (Criteria) this;
        }

        public Criteria andDepartIdEqualTo(Integer value) {
            addCriterion("`depart_id` =", value, "departId");
            return (Criteria) this;
        }

        public Criteria andDepartIdNotEqualTo(Integer value) {
            addCriterion("`depart_id` <>", value, "departId");
            return (Criteria) this;
        }

        public Criteria andDepartIdGreaterThan(Integer value) {
            addCriterion("`depart_id` >", value, "departId");
            return (Criteria) this;
        }

        public Criteria andDepartIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("`depart_id` >=", value, "departId");
            return (Criteria) this;
        }

        public Criteria andDepartIdLessThan(Integer value) {
            addCriterion("`depart_id` <", value, "departId");
            return (Criteria) this;
        }

        public Criteria andDepartIdLessThanOrEqualTo(Integer value) {
            addCriterion("`depart_id` <=", value, "departId");
            return (Criteria) this;
        }

        public Criteria andDepartIdIn(List<Integer> values) {
            addCriterion("`depart_id` in", values, "departId");
            return (Criteria) this;
        }

        public Criteria andDepartIdNotIn(List<Integer> values) {
            addCriterion("`depart_id` not in", values, "departId");
            return (Criteria) this;
        }

        public Criteria andDepartIdBetween(Integer value1, Integer value2) {
            addCriterion("`depart_id` between", value1, value2, "departId");
            return (Criteria) this;
        }

        public Criteria andDepartIdNotBetween(Integer value1, Integer value2) {
            addCriterion("`depart_id` not between", value1, value2, "departId");
            return (Criteria) this;
        }

        public Criteria andUserPostIsNull() {
            addCriterion("`user_post` is null");
            return (Criteria) this;
        }

        public Criteria andUserPostIsNotNull() {
            addCriterion("`user_post` is not null");
            return (Criteria) this;
        }

        public Criteria andUserPostEqualTo(String value) {
            addCriterion("`user_post` =", value, "userPost");
            return (Criteria) this;
        }

        public Criteria andUserPostNotEqualTo(String value) {
            addCriterion("`user_post` <>", value, "userPost");
            return (Criteria) this;
        }

        public Criteria andUserPostGreaterThan(String value) {
            addCriterion("`user_post` >", value, "userPost");
            return (Criteria) this;
        }

        public Criteria andUserPostGreaterThanOrEqualTo(String value) {
            addCriterion("`user_post` >=", value, "userPost");
            return (Criteria) this;
        }

        public Criteria andUserPostLessThan(String value) {
            addCriterion("`user_post` <", value, "userPost");
            return (Criteria) this;
        }

        public Criteria andUserPostLessThanOrEqualTo(String value) {
            addCriterion("`user_post` <=", value, "userPost");
            return (Criteria) this;
        }

        public Criteria andUserPostLike(String value) {
            addCriterion("`user_post` like", value, "userPost");
            return (Criteria) this;
        }

        public Criteria andUserPostNotLike(String value) {
            addCriterion("`user_post` not like", value, "userPost");
            return (Criteria) this;
        }

        public Criteria andUserPostIn(List<String> values) {
            addCriterion("`user_post` in", values, "userPost");
            return (Criteria) this;
        }

        public Criteria andUserPostNotIn(List<String> values) {
            addCriterion("`user_post` not in", values, "userPost");
            return (Criteria) this;
        }

        public Criteria andUserPostBetween(String value1, String value2) {
            addCriterion("`user_post` between", value1, value2, "userPost");
            return (Criteria) this;
        }

        public Criteria andUserPostNotBetween(String value1, String value2) {
            addCriterion("`user_post` not between", value1, value2, "userPost");
            return (Criteria) this;
        }

        public Criteria andUserPhoneIsNull() {
            addCriterion("`user_phone` is null");
            return (Criteria) this;
        }

        public Criteria andUserPhoneIsNotNull() {
            addCriterion("`user_phone` is not null");
            return (Criteria) this;
        }

        public Criteria andUserPhoneEqualTo(String value) {
            addCriterion("`user_phone` =", value, "userPhone");
            return (Criteria) this;
        }

        public Criteria andUserPhoneNotEqualTo(String value) {
            addCriterion("`user_phone` <>", value, "userPhone");
            return (Criteria) this;
        }

        public Criteria andUserPhoneGreaterThan(String value) {
            addCriterion("`user_phone` >", value, "userPhone");
            return (Criteria) this;
        }

        public Criteria andUserPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("`user_phone` >=", value, "userPhone");
            return (Criteria) this;
        }

        public Criteria andUserPhoneLessThan(String value) {
            addCriterion("`user_phone` <", value, "userPhone");
            return (Criteria) this;
        }

        public Criteria andUserPhoneLessThanOrEqualTo(String value) {
            addCriterion("`user_phone` <=", value, "userPhone");
            return (Criteria) this;
        }

        public Criteria andUserPhoneLike(String value) {
            addCriterion("`user_phone` like", value, "userPhone");
            return (Criteria) this;
        }

        public Criteria andUserPhoneNotLike(String value) {
            addCriterion("`user_phone` not like", value, "userPhone");
            return (Criteria) this;
        }

        public Criteria andUserPhoneIn(List<String> values) {
            addCriterion("`user_phone` in", values, "userPhone");
            return (Criteria) this;
        }

        public Criteria andUserPhoneNotIn(List<String> values) {
            addCriterion("`user_phone` not in", values, "userPhone");
            return (Criteria) this;
        }

        public Criteria andUserPhoneBetween(String value1, String value2) {
            addCriterion("`user_phone` between", value1, value2, "userPhone");
            return (Criteria) this;
        }

        public Criteria andUserPhoneNotBetween(String value1, String value2) {
            addCriterion("`user_phone` not between", value1, value2, "userPhone");
            return (Criteria) this;
        }

        public Criteria andUserEmailIsNull() {
            addCriterion("`user_email` is null");
            return (Criteria) this;
        }

        public Criteria andUserEmailIsNotNull() {
            addCriterion("`user_email` is not null");
            return (Criteria) this;
        }

        public Criteria andUserEmailEqualTo(String value) {
            addCriterion("`user_email` =", value, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailNotEqualTo(String value) {
            addCriterion("`user_email` <>", value, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailGreaterThan(String value) {
            addCriterion("`user_email` >", value, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailGreaterThanOrEqualTo(String value) {
            addCriterion("`user_email` >=", value, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailLessThan(String value) {
            addCriterion("`user_email` <", value, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailLessThanOrEqualTo(String value) {
            addCriterion("`user_email` <=", value, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailLike(String value) {
            addCriterion("`user_email` like", value, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailNotLike(String value) {
            addCriterion("`user_email` not like", value, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailIn(List<String> values) {
            addCriterion("`user_email` in", values, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailNotIn(List<String> values) {
            addCriterion("`user_email` not in", values, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailBetween(String value1, String value2) {
            addCriterion("`user_email` between", value1, value2, "userEmail");
            return (Criteria) this;
        }

        public Criteria andUserEmailNotBetween(String value1, String value2) {
            addCriterion("`user_email` not between", value1, value2, "userEmail");
            return (Criteria) this;
        }

        public Criteria andInsTmIsNull() {
            addCriterion("`ins_tm` is null");
            return (Criteria) this;
        }

        public Criteria andInsTmIsNotNull() {
            addCriterion("`ins_tm` is not null");
            return (Criteria) this;
        }

        public Criteria andInsTmEqualTo(Date value) {
            addCriterion("`ins_tm` =", value, "insTm");
            return (Criteria) this;
        }

        public Criteria andInsTmNotEqualTo(Date value) {
            addCriterion("`ins_tm` <>", value, "insTm");
            return (Criteria) this;
        }

        public Criteria andInsTmGreaterThan(Date value) {
            addCriterion("`ins_tm` >", value, "insTm");
            return (Criteria) this;
        }

        public Criteria andInsTmGreaterThanOrEqualTo(Date value) {
            addCriterion("`ins_tm` >=", value, "insTm");
            return (Criteria) this;
        }

        public Criteria andInsTmLessThan(Date value) {
            addCriterion("`ins_tm` <", value, "insTm");
            return (Criteria) this;
        }

        public Criteria andInsTmLessThanOrEqualTo(Date value) {
            addCriterion("`ins_tm` <=", value, "insTm");
            return (Criteria) this;
        }

        public Criteria andInsTmIn(List<Date> values) {
            addCriterion("`ins_tm` in", values, "insTm");
            return (Criteria) this;
        }

        public Criteria andInsTmNotIn(List<Date> values) {
            addCriterion("`ins_tm` not in", values, "insTm");
            return (Criteria) this;
        }

        public Criteria andInsTmBetween(Date value1, Date value2) {
            addCriterion("`ins_tm` between", value1, value2, "insTm");
            return (Criteria) this;
        }

        public Criteria andInsTmNotBetween(Date value1, Date value2) {
            addCriterion("`ins_tm` not between", value1, value2, "insTm");
            return (Criteria) this;
        }

        public Criteria andLeaderIsNull() {
            addCriterion("`leader` is null");
            return (Criteria) this;
        }

        public Criteria andLeaderIsNotNull() {
            addCriterion("`leader` is not null");
            return (Criteria) this;
        }

        public Criteria andLeaderEqualTo(Byte value) {
            addCriterion("`leader` =", value, "leader");
            return (Criteria) this;
        }

        public Criteria andLeaderNotEqualTo(Byte value) {
            addCriterion("`leader` <>", value, "leader");
            return (Criteria) this;
        }

        public Criteria andLeaderGreaterThan(Byte value) {
            addCriterion("`leader` >", value, "leader");
            return (Criteria) this;
        }

        public Criteria andLeaderGreaterThanOrEqualTo(Byte value) {
            addCriterion("`leader` >=", value, "leader");
            return (Criteria) this;
        }

        public Criteria andLeaderLessThan(Byte value) {
            addCriterion("`leader` <", value, "leader");
            return (Criteria) this;
        }

        public Criteria andLeaderLessThanOrEqualTo(Byte value) {
            addCriterion("`leader` <=", value, "leader");
            return (Criteria) this;
        }

        public Criteria andLeaderIn(List<Byte> values) {
            addCriterion("`leader` in", values, "leader");
            return (Criteria) this;
        }

        public Criteria andLeaderNotIn(List<Byte> values) {
            addCriterion("`leader` not in", values, "leader");
            return (Criteria) this;
        }

        public Criteria andLeaderBetween(Byte value1, Byte value2) {
            addCriterion("`leader` between", value1, value2, "leader");
            return (Criteria) this;
        }

        public Criteria andLeaderNotBetween(Byte value1, Byte value2) {
            addCriterion("`leader` not between", value1, value2, "leader");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("`status` is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("`status` is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Byte value) {
            addCriterion("`status` =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Byte value) {
            addCriterion("`status` <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Byte value) {
            addCriterion("`status` >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("`status` >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Byte value) {
            addCriterion("`status` <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Byte value) {
            addCriterion("`status` <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Byte> values) {
            addCriterion("`status` in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Byte> values) {
            addCriterion("`status` not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Byte value1, Byte value2) {
            addCriterion("`status` between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("`status` not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("`create_time` is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("`create_time` is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("`create_time` =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("`create_time` <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("`create_time` >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("`create_time` >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("`create_time` <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("`create_time` <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("`create_time` in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("`create_time` not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("`create_time` between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("`create_time` not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andSystemIdIsNull() {
            addCriterion("`system_id` is null");
            return (Criteria) this;
        }

        public Criteria andSystemIdIsNotNull() {
            addCriterion("`system_id` is not null");
            return (Criteria) this;
        }

        public Criteria andSystemIdEqualTo(Integer value) {
            addCriterion("`system_id` =", value, "systemId");
            return (Criteria) this;
        }

        public Criteria andSystemIdNotEqualTo(Integer value) {
            addCriterion("`system_id` <>", value, "systemId");
            return (Criteria) this;
        }

        public Criteria andSystemIdGreaterThan(Integer value) {
            addCriterion("`system_id` >", value, "systemId");
            return (Criteria) this;
        }

        public Criteria andSystemIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("`system_id` >=", value, "systemId");
            return (Criteria) this;
        }

        public Criteria andSystemIdLessThan(Integer value) {
            addCriterion("`system_id` <", value, "systemId");
            return (Criteria) this;
        }

        public Criteria andSystemIdLessThanOrEqualTo(Integer value) {
            addCriterion("`system_id` <=", value, "systemId");
            return (Criteria) this;
        }

        public Criteria andSystemIdIn(List<Integer> values) {
            addCriterion("`system_id` in", values, "systemId");
            return (Criteria) this;
        }

        public Criteria andSystemIdNotIn(List<Integer> values) {
            addCriterion("`system_id` not in", values, "systemId");
            return (Criteria) this;
        }

        public Criteria andSystemIdBetween(Integer value1, Integer value2) {
            addCriterion("`system_id` between", value1, value2, "systemId");
            return (Criteria) this;
        }

        public Criteria andSystemIdNotBetween(Integer value1, Integer value2) {
            addCriterion("`system_id` not between", value1, value2, "systemId");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("`update_time` is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("`update_time` is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("`update_time` =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("`update_time` <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("`update_time` >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("`update_time` >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("`update_time` <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("`update_time` <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("`update_time` in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("`update_time` not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("`update_time` between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("`update_time` not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andDailyAccessNumIsNull() {
            addCriterion("`daily_access_num` is null");
            return (Criteria) this;
        }

        public Criteria andDailyAccessNumIsNotNull() {
            addCriterion("`daily_access_num` is not null");
            return (Criteria) this;
        }

        public Criteria andDailyAccessNumEqualTo(Integer value) {
            addCriterion("`daily_access_num` =", value, "dailyAccessNum");
            return (Criteria) this;
        }

        public Criteria andDailyAccessNumNotEqualTo(Integer value) {
            addCriterion("`daily_access_num` <>", value, "dailyAccessNum");
            return (Criteria) this;
        }

        public Criteria andDailyAccessNumGreaterThan(Integer value) {
            addCriterion("`daily_access_num` >", value, "dailyAccessNum");
            return (Criteria) this;
        }

        public Criteria andDailyAccessNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("`daily_access_num` >=", value, "dailyAccessNum");
            return (Criteria) this;
        }

        public Criteria andDailyAccessNumLessThan(Integer value) {
            addCriterion("`daily_access_num` <", value, "dailyAccessNum");
            return (Criteria) this;
        }

        public Criteria andDailyAccessNumLessThanOrEqualTo(Integer value) {
            addCriterion("`daily_access_num` <=", value, "dailyAccessNum");
            return (Criteria) this;
        }

        public Criteria andDailyAccessNumIn(List<Integer> values) {
            addCriterion("`daily_access_num` in", values, "dailyAccessNum");
            return (Criteria) this;
        }

        public Criteria andDailyAccessNumNotIn(List<Integer> values) {
            addCriterion("`daily_access_num` not in", values, "dailyAccessNum");
            return (Criteria) this;
        }

        public Criteria andDailyAccessNumBetween(Integer value1, Integer value2) {
            addCriterion("`daily_access_num` between", value1, value2, "dailyAccessNum");
            return (Criteria) this;
        }

        public Criteria andDailyAccessNumNotBetween(Integer value1, Integer value2) {
            addCriterion("`daily_access_num` not between", value1, value2, "dailyAccessNum");
            return (Criteria) this;
        }

        public Criteria andMinuteAccessNumIsNull() {
            addCriterion("`minute_access_num` is null");
            return (Criteria) this;
        }

        public Criteria andMinuteAccessNumIsNotNull() {
            addCriterion("`minute_access_num` is not null");
            return (Criteria) this;
        }

        public Criteria andMinuteAccessNumEqualTo(Integer value) {
            addCriterion("`minute_access_num` =", value, "minuteAccessNum");
            return (Criteria) this;
        }

        public Criteria andMinuteAccessNumNotEqualTo(Integer value) {
            addCriterion("`minute_access_num` <>", value, "minuteAccessNum");
            return (Criteria) this;
        }

        public Criteria andMinuteAccessNumGreaterThan(Integer value) {
            addCriterion("`minute_access_num` >", value, "minuteAccessNum");
            return (Criteria) this;
        }

        public Criteria andMinuteAccessNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("`minute_access_num` >=", value, "minuteAccessNum");
            return (Criteria) this;
        }

        public Criteria andMinuteAccessNumLessThan(Integer value) {
            addCriterion("`minute_access_num` <", value, "minuteAccessNum");
            return (Criteria) this;
        }

        public Criteria andMinuteAccessNumLessThanOrEqualTo(Integer value) {
            addCriterion("`minute_access_num` <=", value, "minuteAccessNum");
            return (Criteria) this;
        }

        public Criteria andMinuteAccessNumIn(List<Integer> values) {
            addCriterion("`minute_access_num` in", values, "minuteAccessNum");
            return (Criteria) this;
        }

        public Criteria andMinuteAccessNumNotIn(List<Integer> values) {
            addCriterion("`minute_access_num` not in", values, "minuteAccessNum");
            return (Criteria) this;
        }

        public Criteria andMinuteAccessNumBetween(Integer value1, Integer value2) {
            addCriterion("`minute_access_num` between", value1, value2, "minuteAccessNum");
            return (Criteria) this;
        }

        public Criteria andMinuteAccessNumNotBetween(Integer value1, Integer value2) {
            addCriterion("`minute_access_num` not between", value1, value2, "minuteAccessNum");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_base
     *
     * @mbggenerated do_not_delete_during_merge Fri Jun 02 17:07:11 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_base
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }
    }
}