package com.entity;

import java.io.Serializable;
import java.util.Date;

public class UserRoleResource implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_role_resource
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    private static final long serialVersionUID = 1L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role_resource.role_resource_id
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    private Integer roleResourceId;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role_resource.role_id
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    private Integer roleId;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role_resource.resource_id
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    private Integer resourceId;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role_resource.create_time
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    private Date createTime;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role_resource.update_time
     *
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role_resource.role_resource_id
     *
     * @return the value of user_role_resource.role_resource_id
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    public Integer getRoleResourceId() {
        return roleResourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role_resource.role_resource_id
     *
     * @param roleResourceId the value for user_role_resource.role_resource_id
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    public void setRoleResourceId(Integer roleResourceId) {
        this.roleResourceId = roleResourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role_resource.role_id
     *
     * @return the value of user_role_resource.role_id
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role_resource.role_id
     *
     * @param roleId the value for user_role_resource.role_id
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role_resource.resource_id
     *
     * @return the value of user_role_resource.resource_id
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    public Integer getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role_resource.resource_id
     *
     * @param resourceId the value for user_role_resource.resource_id
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    public void setResourceId(Integer resourceId) {
        this.resourceId = resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role_resource.create_time
     *
     * @return the value of user_role_resource.create_time
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role_resource.create_time
     *
     * @param createTime the value for user_role_resource.create_time
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role_resource.update_time
     *
     * @return the value of user_role_resource.update_time
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role_resource.update_time
     *
     * @param updateTime the value for user_role_resource.update_time
     * @mbggenerated Fri Jun 02 17:07:11 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}